INSERT INTO ONLINE_EXAM_USERS(USER_IS_ADMIN, FIRST_NAME, LAST_NAME, EMAIL,PASSWORD)
VALUES('T', 'ARITRA', 'RUDRA', 'aritrarudra@gmail.com', 'abc123');

INSERT INTO ONLINE_EXAM_USERS(USER_IS_ADMIN, FIRST_NAME, LAST_NAME, EMAIL,PASSWORD)
VALUES('T', 'A', 'Z', 'a', 'a');

